# Generated by Django 4.1.2 on 2022-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('action', models.CharField(choices=[('no_filter', 'No Filter'), ('colorized', 'Colorized'), ('grayscale', 'Grayscale'), ('blurred', 'Blurred'), ('binary', 'Binary'), ('invert', 'Invert')], default='no_filter', max_length=20)),
                ('filtered_image', models.ImageField(upload_to='filtered')),
            ],
        ),
    ]
