# Generated by Django 4.1.2 on 2022-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_upload_created_upload_updated_alter_upload_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='filtered'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('no filter', 'No Filter'), ('colorized', 'Colorized'), ('grayscale', 'Grayscale'), ('blurred', 'Blurred'), ('binary', 'Binary'), ('invert', 'Invert')], default='no filter', max_length=50),
        ),
    ]
